version: '3.8'

services:
  app:
    container_name: demo-toolbox-front-container
    image: node:16-alpine
    entrypoint: /bin/sh
    volumes:
      - .:/app
    tty: true
    ports:
      - "3000:3000"
    working_dir: /app
    env_file:
      - .env
